/*
# [Operation] Create Generated Scripts Table
Creates the table to store scripts generated by users.

## Query Description:
This script creates the `generated_scripts` table. This allows users to save the JavaScript code they generate, along with its configuration, so they can retrieve it later.

## Metadata:
- Schema-Category: "Data"
- Impact-Level: "Medium"
- Requires-Backup: false
- Reversible: true (by dropping the table)

## Structure Details:
- Table: `public.generated_scripts`
- Columns: `id`, `user_id`, `name`, `script_code`, `config`, `campaign_ids`, `script_type`, `created_at`
- Constraints: Primary Key on `id`, Foreign Key on `user_id` referencing `public.profiles.id`.

## Security Implications:
- RLS Status: Not enabled by this script.
- Policy Changes: No
- Auth Requirements: None.

## Performance Impact:
- Indexes: Primary key and foreign key indexes.
- Triggers: None.
- Estimated Impact: Low.
*/

-- Create the generated_scripts table
CREATE TABLE public.generated_scripts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    name TEXT NOT NULL,
    script_code TEXT NOT NULL,
    config JSONB NOT NULL,
    campaign_ids TEXT[] NOT NULL,
    script_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments
COMMENT ON TABLE public.generated_scripts IS 'Stores popunder scripts generated by users.';
