/*
# Create generated_scripts table
Stores scripts generated by users.

## Query Description:
Creates the `generated_scripts` table to save the JavaScript code and configuration generated by users.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Medium"
- Requires-Backup: false
- Reversible: true

## Structure Details:
- Table: public.generated_scripts
- Columns: id, user_id, name, script_code, config, campaign_ids, script_type, created_at
- Constraints: Foreign Key to public.profiles

## Security Implications:
- RLS Status: Disabled (will be enabled in a later step)
- Policy Changes: No
- Auth Requirements: Linked to user profiles.

## Performance Impact:
- Indexes: Primary key and foreign key indexes.
- Triggers: None
- Estimated Impact: Low
*/
create table public.generated_scripts (
    id uuid not null default gen_random_uuid(),
    user_id uuid not null references public.profiles on delete cascade,
    name text not null,
    script_code text not null,
    config jsonb not null,
    campaign_ids text[] not null,
    script_type text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (id)
);
alter table public.generated_scripts enable row level security;
